/**
 * Pack a schema into a downloadable zip:
 *   <slug>/
 *     index.html       – the rendered prototype, double-clickable
 *     schema.json      – canonical artefact
 *     README.txt       – plain-language instructions for the recipient
 */

import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import type { FormSchema } from '../types/schema';
import { exportSchemaToHtml } from './export-html';
import { slugify } from './slug';

export async function downloadSchemaZip(schema: FormSchema): Promise<string> {
  const slug = slugify(schema.id || schema.meta.title || 'prototype');
  const zip = new JSZip();
  const folder = zip.folder(slug)!;

  folder.file('index.html', exportSchemaToHtml(schema));
  folder.file('schema.json', JSON.stringify(schema, null, 2));
  folder.file('README.txt', buildReadme(schema));

  const blob = await zip.generateAsync({ type: 'blob' });
  saveAs(blob, `${slug}.zip`);
  return slug;
}

function buildReadme(schema: FormSchema): string {
  return `${schema.meta.title}
${'='.repeat(schema.meta.title.length)}

How to view this prototype
--------------------------
1. Unzip this folder.
2. Double-click index.html.
3. It opens in your browser. Click "Start now" to walk through the form.

Files in this folder
--------------------
  index.html    The clickable prototype. No internet connection needed
                beyond the design-system fonts and styles loaded from
                public CDNs.
  schema.json   The structured form definition. This is the canonical
                artefact — the prototype HTML is built from it.
  README.txt    This file.

About this prototype
--------------------
  MDA            ${schema.meta.mda || '(not set)'}
  Status         ${schema.meta.status}
  Pages          ${schema.flow.length}
  Reference tag  ${schema.meta.referencePrefix}
  Last updated   ${schema.meta.lastUpdated ?? '(not set)'}

Generated by the GovTech Barbados Form Generator (v2).
`;
}
